### ISSUE TITLE
oyranos-0.9.5 /src/modules/oyranos_cmm_oyIM_profile.c:941: possible bad comparison ?

### ISSUE THREAD

**Issue by dcb314** [oyranos-cms/oyranos#11]
oyranos-0.9.5/src/modules/oyranos_cmm_oyIM_profile.c:941:48: warning: comparison of constant 
'12' with boolean expression is always false [-Wbool-compare]

   error = !mem || !oyProfileTag_GetSize(tag) > 12;

Suggest add (). Maybe

   error = (!mem) || (oyProfileTag_GetSize(tag) <= 12);

**Comment by beku** [comment]
thanks for reporting and the patch

is in commit #b6a45ae80d53dd2cae174fa20233f717e28598ec
