### ISSUE TITLE
Add support for a Qt5 environment

### ISSUE THREAD

**Issue by sl1pkn07** [oyranos-cms/oyranos#12]
Hi

now is only compatible with Qt4.

any plans to add compatibility with Qt5?

greetings

**Comment by beku** [comment]
The Oyranos library, modules and command line tools do not depend on toolkits.
What do specifically mean with "now is only compatible with Qt4"?

(The only diagnostic applet inside Oyranos with Qt dependency is qcmsevents, which lacks porting to Qt5.)

**Comment by sl1pkn07** [comment]
(The only diagnostic applet inside Oyranos with Qt dependency is qcmsevents, which lacks porting to Qt5.)
^ this

**Comment by beku** [comment]
a first version of qcmsevents is in git; it compiles and runs, but still needs work on some edges

**Comment by sl1pkn07** [comment]
thanks

**Comment by sl1pkn07** [comment]
oabout this enhancement

is possible make Qt4 and Qt5 qcmsevents co-intalable?

greetings

**Comment by beku** [comment]
The old functionality from Qt4 now match the Qt5 version in git master. Feel free to close.
