### ISSUE TITLE
../liboyranos_core/liboyranos_core-static.a(oyranos_io_core.c.o): In function `oyGetTempFileName_': oyranos_io_core.c:(.text+0x1dde): warning: the use of `tmpnam' is dangerous, better use `mkstemp'

### ISSUE THREAD

**Issue by sl1pkn07** [oyranos-cms/oyranos#13]
log: (snip)

http://sl1pkn07.wtf/paste/view/b7049559

Gcc 4.9.0

greetings

**Comment by beku** [comment]
The title of this issue is a warning only. The linking of qcmsevents, as shown in the linked log fails.

I can reproduce. There was a old library name used, which no one noticed. Fixed in git.
Thanks for reporting
