### ISSUE TITLE
fail build: missing 'doc_alpha/html/'

### ISSUE THREAD

**Issue by sl1pkn07** [oyranos-cms/oyranos#14]
[ 97%] Error: tag HTML_HEADER: header file `/home/sl1pkn07/aplicaciones/oyranos-git/src/oyranos/doc/doxygen.header' does not exist
    cp: cannot create regular file 'doc_alpha/html/': No such file or directory
    doc/CMakeFiles/docu.dir/build.make:51: recipe for target 'doc/html' failed
    make[2]: *** [doc/html] Error 1
    CMakeFiles/Makefile2:2983: recipe for target 'doc/CMakeFiles/docu.dir/all' failed
    make[1]: *** [doc/CMakeFiles/docu.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....

creating the doc/doc_alpha/html/ by hand solve the problem

test with -j1 and -j24 (if the problem is a multithread)

      mkdir -p build && cd build
      cmake ../oyranos \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release
      make

doxygen 1.8.9.1

greetings

**Comment by beku** [comment]
should be fixed in git; where some not renamed file names
and thanks for reporting

**Comment by beku** [comment]
a first Qt5 version is in git, still needs work on some edges
