### ISSUE TITLE
commit c7e283c fail build

### ISSUE THREAD

**Issue by sl1pkn07** [oyranos-cms/oyranos#15]
libx11 1.6.3

[ 96%] Building CXX object src/tools/qcmsevents/CMakeFiles/qcmsevents.dir/qcmsevents.cpp.o
In file included from /home/sl1pkn07/aplicaciones/oyranos-git/src/oyranos/src/tools/qcmsevents/qcmsevents.cpp:13:0:
/home/sl1pkn07/aplicaciones/oyranos-git/src/oyranos/src/tools/qcmsevents/qcmsevents.h: In member function 'void Qcmse::setup()':
/home/sl1pkn07/aplicaciones/oyranos-git/src/oyranos/src/tools/qcmsevents/qcmsevents.h:113:16: error: variable 'QX11Info i' has initializer but incomplete type
       QX11Info i = d->x11Info();
                ^
src/tools/qcmsevents/CMakeFiles/qcmsevents.dir/build.make:68: recipe for target 'src/tools/qcmsevents/CMakeFiles/qcmsevents.dir/qcmsevents.cpp.o' failed
make[2]: *** [src/tools/qcmsevents/CMakeFiles/qcmsevents.dir/qcmsevents.cpp.o] Error 1
CMakeFiles/Makefile2:2339: recipe for target 'src/tools/qcmsevents/CMakeFiles/qcmsevents.dir/all' failed
make[1]: *** [src/tools/qcmsevents/CMakeFiles/qcmsevents.dir/all] Error 2

greetings

**Comment by beku** [comment]
agreed. A header was removed from Qt4 sources. Should be fixed in git
Thanks
