### ISSUE TITLE
cmake doesn't check glu-devel

### ISSUE THREAD

**Issue by tari3x** [oyranos-cms/oyranos#44]
My compilation failed with
Oy_Fl_Shader_Box.h:11:22: fatal error: GL/glu.h: No such file or directory
 #  include <GL/glu.h>

**Comment by beku** [comment]
@tari3x Does the last commit listed here fix this issue for you?

**Comment by tari3x** [comment]
I don't remember seeing this when compiling again recently, so maybe it got fixed. Happy to close.

**Comment by beku** [comment]
Thanks for the reply
