### ISSUE TITLE
Could not resolve device 0. Available devices: 0

### ISSUE THREAD

**Issue by tari3x** [oyranos-cms/oyranos#45]
```
./src/tools/oyranos-monitor -d 0 ITULab.icc
WARNING 0.006300: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006393: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006411: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.006473: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006527: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006542: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.006592: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006639: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006654: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.006701: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006749: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006764: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.006809: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006856: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006871: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.006915: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006962: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.006976: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.007045: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007063: [-1] oyranos_devices.c:3255 oyFilterNode_FromOptions() no pattern from policy module for base_pattern obtained: "//openicc/icc_color"
WARNING 0.007079: [-1] oyranos_devices.c:3262 oyFilterNode_FromOptions() could not create new core: "---" "//openicc/icc_color"
WARNING 0.007090: [-1] oyranos_devices.c:3266 oyFilterNode_FromOptions() pattern pointer freed
WARNING 0.007103: [-1] oyranos_devices.c:3266 oyFilterNode_FromOptions() nothing to delete pattern
WARNING 0.007156: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007204: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007219: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.007264: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007311: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007325: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.007370: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007416: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007429: [-1] oyranos_db.c:203 oyDbInitialise_()  can't properly call "db_handler" e:-1
WARNING 0.007480: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
WARNING 0.007498: [-1] oyranos_devices.c:3319 oyFilterNode_FromOptions() could not create new node: --- //openicc/icc_color
WARNING 0.007512: [-1] oyranos_devices.c:3325 oyFilterNode_FromOptions() pattern pointer freed
WARNING 0.007523: [-1] oyranos_devices.c:3325 oyFilterNode_FromOptions() nothing to delete pattern
WARNING 0.007613: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
Could not resolve device 0. Available devices: 0
WARNING 0.007701: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
```

**Comment by beku** [comment]
This printout looks like a library missmatch. Are the local ompiled libraries and modules installed and seen by the ./src/tools/oyranos-monitor tool?
Try (on Linux):

      mkdir build
      cd build
      cmake -DCMAKE_INSTALL_PATH=~/.local
      make
      make install
      which oyranos-monitor
      ldd ~/.local/bin/oyranos-monitor

**Comment by tari3x** [comment]
Making with "-DCMAKE_INSTALL_PATH=~/.local" doesn't have any effect: it still tries installing into /usr/local/bin (do I need to distclean first or something?). Here's the ldd of /usr/local/bin/oyranos-monitor:

'''
>which oyranos-monitor 
/usr/local/bin/oyranos-monitor
> ldd /usr/local/bin/oyranos-monitor
        linux-vdso.so.1 (0x00007ffe56f7f000)
        libOyranos.so.0 => /usr/lib64/libOyranos.so.0 (0x00007f0662b27000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f066282a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f0662485000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007f066211c000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0661f18000)
        libyajl.so.2 => /usr/lib64/libyajl.so.2 (0x00007f0661d0e000)
        libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f0661b06000)
        libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f06618e9000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f06615ab000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f0661399000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f0661193000)
        libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f0660f88000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f0660d85000)
        libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f0660b7f000)
        libXmu.so.6 => /usr/lib64/libXmu.so.6 (0x00007f0660964000)
        libXt.so.6 => /usr/lib64/libXt.so.6 (0x00007f06606fd000)
        libOyranosConfig.so.0 => /usr/lib64/libOyranosConfig.so.0 (0x00007f06604a4000)
        libOyranosModules.so.0 => /usr/lib64/libOyranosModules.so.0 (0x00007f066026d000)
        libOyranosObject.so.0 => /usr/lib64/libOyranosObject.so.0 (0x00007f0660040000)
        libOyranosCore.so.0 => /usr/lib64/libOyranosCore.so.0 (0x00007f065fe25000)
        libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f065fbf5000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f065f9d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0662d4d000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f065f7c2000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f065f599000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f065f394000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f065f174000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f065ef6a000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f065ed66000)
'''

Regardless of the underlying problem, it's sad that the error message is nonsensical.

**Comment by tari3x** [comment]
Hmm, I tried running this again, and it works better (at least the error message is gone). The only obvious thing that changed from the original report is I ran "make install" in the meantime. I thought "make install" was not necessary if you are happy to run the binary from the compilation directory, but I guess my mental model is wrong?

```
 ./src/tools/oyranos-monitor -d 0 ITULab.icc
WARNING 0.005134: [-1] oyCMMapi_s_.c:645 oyCMMapi_Check_() Found problems with: oyCMMapi5_s MetaFilter org/oyranos/openicc/oyIM 0.0.2(0.9.6)
Warning - Unable to read file 'ITULab.icc'
WARNING 0.031880: oyOptions_s[542]="" oyranos_monitor_x11_extend.c:123 oyX1ColorServer_Handle() color_server_active.source_data: 0
WARNING 0.034671: oyProfile_s[282]="/usr/share/color/icc/Oyranos/ITULab.icc" oyranos_monitor_effect.c:216 oyProfile_GetVCGT() vcgt tag size too small 0 ITULab

Warning - green gamma table not monotonic
Warning - green gamma table not monotonic
```

Happy to consider this case closed for now.

**Comment by beku** [comment]
Glad to read you could test it.

    oyranos-monitor -lcv # should verify the profile is in the DB.

(The binaries are not linked by default dynamically for normal Linux desktop builds. The devel source tree is as of this writing at version 0.9.7, while your installation in /usr/lib64 is 0.9.6. So you see these warnings.)
