### ISSUE TITLE
Can't compile on Arch Linux

### ISSUE THREAD

**Issue by jasuka** [oyranos-cms/oyranos#61]
Hello,

Oyranos fails to build on Arch Linux when Qt enabled.

Qt version: 5.15.0

I've attached the build error.
[oyranos.txt](https://github.com/oyranos-cms/oyranos/files/5084155/oyranos.txt)

**Comment by beku** [comment]
Here a patch for the issue. Hope this helps for you.

From 38b721844703a267bb2721cbcef471ee3aa33fb9 Mon Sep 17 00:00:00 2001
From: Kai-Uwe Behrmann <ku.b@gmx.de>
Date: Tue, 4 Feb 2020 14:03:06 +0100
Subject: * [tools]: fix Qt-5.14 compile error with X11::None

Error (openSUSE-Tumbleweed, gcc):
/usr/include/qt5/QtWidgets/qactiongroup.h:64:9: error: expected identifier before numeric constant
   64 |         None,
      |         ^~~~

X11 and Qt headers contain 'None' declarations:
/usr/include/X11/X.h:#define None                 0L    /* universal null resource or null atom */
versus
/usr/include/qt5/QtWidgets/qactiongroup.h:   enum class ExclusionPolicy {
/usr/include/qt5/QtWidgets/qactiongroup.h:        None,

diff --git a/src/tools/qcmsevents/qcmsevents.cpp b/src/tools/qcmsevents/qcmsevents.cpp
index b0130a11..08a139d4 100644
--- a/src/tools/qcmsevents/qcmsevents.cpp
+++ b/src/tools/qcmsevents/qcmsevents.cpp
@@ -21,6 +21,11 @@

 #include <X11/Xcm/Xcm.h>

+#ifdef None
+// is defined in X11 as 0L, which collides with various "enum class None" declarations in Qt
+#undef None
+#endif
+
 #include <QAction>
 #include <QActionGroup>
 #include <QVBoxLayout>

**Comment by jasuka** [comment]
Thank you. It works perfectly :+1:

**Comment by arifzeeshan** [comment]
I'm getting build failure on 0.9.6, using AUR version. 

`Consolidate compiler generated dependencies of target openicc-static
[  2%] Built target openicc-static
[  2%] Extract translatable messages to /home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/po/oyranos.pot
[  3%] Generating cs.gmo
............................................................................................................... done.
576 translated messages, 209 fuzzy translations, 158 untranslated messages.
[  3%] Generating de.gmo
......................................................................................................... done.
888 translated messages, 3 fuzzy translations, 52 untranslated messages.
[  3%] Generating eo.gmo
........................................................................................................ done.
32 translated messages, 86 fuzzy translations, 825 untranslated messages.
[  3%] Generating eu.gmo
...................................................................................................... done.
146 translated messages, 323 fuzzy translations, 474 untranslated messages.
[  4%] Generating fr.gmo
............................................................................................................... done.
71 translated messages, 285 fuzzy translations, 587 untranslated messages.
[  4%] Generating ru.gmo
................................................................................................................ done.
12 translated messages, 3 fuzzy translations, 928 untranslated messages.
[  4%] Built target translations_1
Consolidate compiler generated dependencies of target OyranosCore
[  6%] Built target OyranosCore
Consolidate compiler generated dependencies of target oyranos_core-static
[  8%] Built target oyranos_core-static
Consolidate compiler generated dependencies of target OyranosObject
[ 15%] Built target OyranosObject
Consolidate compiler generated dependencies of target oyranos_object-static
[ 21%] Built target oyranos_object-static
Consolidate compiler generated dependencies of target OyranosModules
[ 34%] Built target OyranosModules
Consolidate compiler generated dependencies of target oyranos_modules-static
[ 46%] Built target oyranos_modules-static
Consolidate compiler generated dependencies of target OyranosConfig
[ 52%] Built target OyranosConfig
Consolidate compiler generated dependencies of target oyranos_config-static
[ 58%] Built target oyranos_config-static
Consolidate compiler generated dependencies of target Oyranos
[ 62%] Built target Oyranos
Consolidate compiler generated dependencies of target oyranos-static
[ 67%] Built target oyranos-static
Consolidate compiler generated dependencies of target oyranos_lcms_cmm_module
[ 67%] Built target oyranos_lcms_cmm_module
Consolidate compiler generated dependencies of target oyranos_lcm2_cmm_module
[ 68%] Built target oyranos_lcm2_cmm_module
Consolidate compiler generated dependencies of target oyranos_lraw_cmm_module
[ 69%] Built target oyranos_lraw_cmm_module
Consolidate compiler generated dependencies of target oyranos_oicc_cmm_module
[ 69%] Built target oyranos_oicc_cmm_module
Consolidate compiler generated dependencies of target oyranos_oPNG_cmm_module
[ 70%] Built target oyranos_oPNG_cmm_module
Consolidate compiler generated dependencies of target oyranos_oJPG_cmm_module
[ 70%] Built target oyranos_oJPG_cmm_module
Consolidate compiler generated dependencies of target oyranos_oydi_cmm_module
[ 70%] Built target oyranos_oydi_cmm_module
Consolidate compiler generated dependencies of target oyranos_oyra_cmm_module
[ 72%] Built target oyranos_oyra_cmm_module
Consolidate compiler generated dependencies of target oyranos_trds_cmm_module
[ 73%] Built target oyranos_trds_cmm_module
Consolidate compiler generated dependencies of target oyranos_oiDB_cmm_module
[ 74%] Built target oyranos_oiDB_cmm_module
Consolidate compiler generated dependencies of target oyranos_elDB_cmm_module
[ 74%] Building C object src/modules/color/modules/CMakeFiles/oyranos_elDB_cmm_module.dir/oyranos_cmm_elDB.c.o
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���oyGetByName���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:133:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  133 |   Key * error_key = keyNew(KEY_END);
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:134:30: warning: passing argument 1 of ���kdbOpen��� from incompatible pointer type [-Wincompatible-pointer-types]
  134 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                              ^~~~~~~~~
      |                              |
      |                              Key * {aka struct _Key *}
In file included from /home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:84:
/usr/include/elektra/kdb.h:128:31: note: expected ���const KeySet *��� {aka ���const struct _KeySet *���} but argument is of type ���Key *��� {aka ���struct _Key *���}
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |                ~~~~~~~~~~~~~~~^~~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:134:22: error: too few arguments to function ���kdbOpen���
  134 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                      ^~~~~~~
/usr/include/elektra/kdb.h:128:7: note: declared here
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���oyGetKey���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:172:3: error: too few arguments to function ���keyCopy���
  172 |   keyCopy( key, result );
      |   ^~~~~~~
/usr/include/elektra/kdb.h:147:7: note: declared here
  147 | Key * keyCopy (Key *dest, const Key *source, elektraCopyFlags flags);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���oySetKey���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:183:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  183 |   Key * error_key = keyNew(KEY_END);
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:184:30: warning: passing argument 1 of ���kdbOpen��� from incompatible pointer type [-Wincompatible-pointer-types]
  184 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                              ^~~~~~~~~
      |                              |
      |                              Key * {aka struct _Key *}
/usr/include/elektra/kdb.h:128:31: note: expected ���const KeySet *��� {aka ���const struct _KeySet *���} but argument is of type ���Key *��� {aka ���struct _Key *���}
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |                ~~~~~~~~~~~~~~~^~~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:184:22: error: too few arguments to function ���kdbOpen���
  184 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                      ^~~~~~~
/usr/include/elektra/kdb.h:128:7: note: declared here
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:194:17: error: too few arguments to function ���keyDup���
  194 |     Key * dup = keyDup (key);
      |                 ^~~~~~
/usr/include/elektra/kdb.h:215:20: note: declared here
  215 | static inline Key *keyDup (const Key *source, elektraCopyFlags flags)
      |                    ^~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���elDB_newFrom���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:361:5: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  361 |     db->error = keyNew(KEY_END);
      |     ^~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:362:23: warning: passing argument 1 of ���kdbOpen��� from incompatible pointer type [-Wincompatible-pointer-types]
  362 |     db->h = kdbOpen(db->error);
      |                     ~~^~~~~~~
      |                       |
      |                       Key * {aka struct _Key *}
/usr/include/elektra/kdb.h:128:31: note: expected ���const KeySet *��� {aka ���const struct _KeySet *���} but argument is of type ���Key *��� {aka ���struct _Key *���}
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |                ~~~~~~~~~~~~~~~^~~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:362:13: error: too few arguments to function ���kdbOpen���
  362 |     db->h = kdbOpen(db->error);
      |             ^~~~~~~
/usr/include/elektra/kdb.h:128:7: note: declared here
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���elDBSetString���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:600:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  600 |   Key * error_key = keyNew(KEY_END);
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:601:30: warning: passing argument 1 of ���kdbOpen��� from incompatible pointer type [-Wincompatible-pointer-types]
  601 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                              ^~~~~~~~~
      |                              |
      |                              Key * {aka struct _Key *}
/usr/include/elektra/kdb.h:128:31: note: expected ���const KeySet *��� {aka ���const struct _KeySet *���} but argument is of type ���Key *��� {aka ���struct _Key *���}
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |                ~~~~~~~~~~~~~~~^~~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:601:22: error: too few arguments to function ���kdbOpen���
  601 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                      ^~~~~~~
/usr/include/elektra/kdb.h:128:7: note: declared here
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:637:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  637 |   key = keyNew( KEY_END );
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���elDBSearchEmptyKeyname���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:691:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  691 |   Key * error_key = keyNew(KEY_END);
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:692:30: warning: passing argument 1 of ���kdbOpen��� from incompatible pointer type [-Wincompatible-pointer-types]
  692 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                              ^~~~~~~~~
      |                              |
      |                              Key * {aka struct _Key *}
/usr/include/elektra/kdb.h:128:31: note: expected ���const KeySet *��� {aka ���const struct _KeySet *���} but argument is of type ���Key *��� {aka ���struct _Key *���}
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |                ~~~~~~~~~~~~~~~^~~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:692:22: error: too few arguments to function ���kdbOpen���
  692 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                      ^~~~~~~
/usr/include/elektra/kdb.h:128:7: note: declared here
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: In function ���elDBEraseKey���:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:744:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  744 |   Key * error_key = keyNew(KEY_END);
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:745:30: warning: passing argument 1 of ���kdbOpen��� from incompatible pointer type [-Wincompatible-pointer-types]
  745 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                              ^~~~~~~~~
      |                              |
      |                              Key * {aka struct _Key *}
/usr/include/elektra/kdb.h:128:31: note: expected ���const KeySet *��� {aka ���const struct _KeySet *���} but argument is of type ���Key *��� {aka ���struct _Key *���}
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |                ~~~~~~~~~~~~~~~^~~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:745:22: error: too few arguments to function ���kdbOpen���
  745 |   KDB * oy_handle_ = kdbOpen(error_key); oyERRopen(error_key)
      |                      ^~~~~~~
/usr/include/elektra/kdb.h:128:7: note: declared here
  128 | KDB * kdbOpen (const KeySet * contract, Key *parentKey);
      |       ^~~~~~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:746:3: warning: not enough variable arguments to fit a sentinel [-Wformat=]
  746 |   Key * top =  keyNew(KEY_END);
      |   ^~~
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c: At top level:
/home/arif/.config/trizen/sources/oyranos/src/oyranos-0.9.6/src/modules/color/modules/oyranos_cmm_elDB.c:801:42: error: ���KDB_VERSION_MICRO��� undeclared here (not in a function); did you mean ���KDB_VERSION_MINOR���?
  801 |   {KDB_VERSION_MAJOR, KDB_VERSION_MINOR, KDB_VERSION_MICRO}, /**< lib_version */
      |                                          ^~~~~~~~~~~~~~~~~
      |                                          KDB_VERSION_MINOR
make[2]: *** [src/modules/color/modules/CMakeFiles/oyranos_elDB_cmm_module.dir/build.make:76: src/modules/color/modules/CMakeFiles/oyranos_elDB_cmm_module.dir/oyranos_cmm_elDB.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1475: src/modules/color/modules/CMakeFiles/oyranos_elDB_cmm_module.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
`

**Comment by arifzeeshan** [comment]
> 
This patch gives me an error 

```
tarting prepare()...
patching file src/tools/qcmsevents/qcmsevents.cpp
patch unexpectedly ends in middle of line
patch: **** unexpected end of file in patch
==> ERROR: A failure occurred in prepare().

```
