### ISSUE TITLE
Build error on Artix Linux

### ISSUE THREAD

**Issue by 3rgoProxy** [oyranos-cms/oyranos#72]
Hello! I'm a bit of a llinux noob and have only been using linux as a daily driver for the past few months. I installed oyranos successfully about a month ago but had to do a clean install of my os two days ago. Since then I've been trying to recompile oyranos and I keep getting the same errors no matter what I've been trying. I can't seem to find a solution online anywhere so I'm making this post here. As I've said I'm a noob so it's probably something I've done wrong. If you need more detailed error logs and so on please be specific on how it should be retrieved since I more than likely don't yet know how to do it but will more than happy for the new information. Here are the errors I get during the build: 

[ 75%] Building CXX object src/modules/color/modules/devices/CMakeFiles/oyranos_oyRE_cmm_module.dir/oyranos_cmm_oyRE.cpp.o
/home/dale/pac/oyranos/src/oyranos-0.9.6/src/modules/color/modules/devices/oyranos_cmm_oyRE.cpp:485:26: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
  485 |       const char * reg = "//"OY_TYPE_STD"/create_profile.color_matrix.icc";
      |                          ^
/home/dale/pac/oyranos/src/oyranos-0.9.6/src/modules/color/modules/devices/oyranos_cmm_oyRE.cpp: In function ‘int DeviceFromContext(oyConfig_s**, libraw_output_params_t*)’:
/home/dale/pac/oyranos/src/oyranos-0.9.6/src/modules/color/modules/devices/oyranos_cmm_oyRE.cpp:1450:20: error: ‘struct libraw_output_params_t’ has no member named ‘shot_select’
 1450 |    DFC_OPT_ADD_INT(shot_select)
      |                    ^~~~~~~~~~~
/home/dale/pac/oyranos/src/oyranos-0.9.6/src/modules/color/modules/devices/oyranos_cmm_oyRE.cpp:1395:47: note: in definition of macro ‘DFC_OPT_ADD_INT’
 1395 |                                       params->name, 0, OY_CREATE_NEW );
      |                                               ^~~~
make[2]: *** [src/modules/color/modules/devices/CMakeFiles/oyranos_oyRE_cmm_module.dir/build.make:76: src/modules/color/modules/devices/CMakeFiles/oyranos_oyRE_cmm_module.dir/oyranos_cmm_oyRE.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1471: src/modules/color/modules/devices/CMakeFiles/oyranos_oyRE_cmm_module.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

I hope that is sufficient information! Any idea what I should do to resolve the issue?

**Comment by beku** [comment]
Those compile issues should be fixed in git.
(There was no release since years.)
